export const FETCH_PHOTO = 'FETCH_PHOTO';
export const DELETE_PHOTO = 'DELETE_PHOTO';
export const DELETE_PHOTO_OPTIMISTIC = 'DELETE_PHOTO_OPTIMISTIC';
export const FETCH_POSTS = 'FETCH_POSTS';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_OPTIMISTIC = 'DELETE_POST_OPTIMISTIC';
