export const FETCH_PHOTO = 'FETCH_PHOTO';
export const CLEAR_PHOTO = 'CLEAR_PHOTO';
export const FETCH_POST = 'FETCH_POST';
export const CLEAR_POST = 'CLEAR_POST';
export const CANCEL_FETCH_POST = 'CANCEL_FETCH_POST';
export const INCREMENT_REQUEST_COUNTER = 'INCREMENT_REQUEST_COUNTER';
export const INCREMENT_RESPONSE_COUNTER = 'INCREMENT_RESPONSE_COUNTER';
export const INCREMENT_ERROR_COUNTER = 'INCREMENT_ERROR_COUNTER';
